### ISSUE TITLE
$ref overwrites `nullable` property

### ISSUE THREAD

**Issue by bushkov** [Pylons/pyramid_openapi3#159]
If a property is defined via a `$ref` and it's `nullable` set to `True`, then this nullable will be ignored.

If you take an example from the [TODO app](https://github.com/Pylons/pyramid_openapi3/tree/master/examples/todoapp), make a `title` nullable:
```
    Item:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 40
          nullable: true
```
and modify `ITEMS` in `app.py` to contain an item with `null` property:
```python
ITEMS = [
    Item(title="Buy milk"),
    Item(title="Buy eggs"),
    Item(title="Make pankaces!"),
    Item(title=None),
]
```
Then everything works fine.

However, if we define `title` via a `$ref`:
```
    Title:
      type: string
      maxLength: 40
      nullable: true

    Item:
      type: object
      required:
        - title
      properties:
        title:
          $ref: '#/components/schemas/Title'
```

Then we get the following error:
```
Value [{'title': 'Buy milk'}, {'title': 'Buy eggs'}, {'title': 'Make pankaces!'}, {'title': None}] not valid for schema of type SchemaType.ARRAY: (<ValidationError: 'None for not nullable'>,)
```

Note that we started observing this error only since yesterday, before it was working as expected.

**Comment by zupo** [comment]
Thanks for the bug report!

> Note that we started observing this error only since yesterday, before it was working as expected.

What changed since yesterday? Did some dependency get upgraded? This looks like it might be a bug in https://github.com/p1c2u/openapi-core (that pyramid_openapi3 depends on).

**Comment by bushkov** [comment]
> What changed since yesterday? 

That's the mystery for us, since no packages that we explicitly use have been updated since the last couple of days. Might be one of the implicit dependencies of those packages.`

On our side https://github.com/p1c2u/openapi-core is frozen to version 0.13.8, because one of the dependencies requires version of openapi-core to be < 0.14. So at least openapi-core remained the same on our side.

On our side

**Comment by bushkov** [comment]
It seems the offending implicit dependency package that causes this issue is `jsonschema`. We started having this issue once it was [updated](https://pypi.org/project/jsonschema/4.0.1/#history) from `3.2.0` to `4.0.1`. If we downgrade `jsonschema` back to `3.2.0`, everything works fine.

**Comment by bushkov** [comment]
I have noticed something which might be related to this issue. We have the following warning from `jsonschema` when using `pyramid_openapi3`:
```
jsonschema/validators.py:190: DeprecationWarning: Passing a schema to Validator.iter_errors is deprecated and will be removed in a future release. Call validator.evolve(schema=new_schema).iter_errors(...) instead
```

And in `openapi-schema-validator`, `iter_errors` [overwrites](https://github.com/p1c2u/openapi-schema-validator/blob/master/openapi_schema_validator/validators.py#L70) `nullable` parameter setting it to `False`.

**Comment by zupo** [comment]
Hey @bushkov, did you manage to resolve this, or is the issue still there?

**Comment by bushkov** [comment]
> Hey @bushkov, did you manage to resolve this, or is the issue still there?

No, the issue is still there.

**Comment by zupo** [comment]
The underlying problem seems to have been addressed in `openapi-schema-validator` recently: https://github.com/p1c2u/openapi-schema-validator/issues/22.

**Comment by bushkov** [comment]
@zupo Any update on this issue? I still get `ValidationError: 'None for not nullable'` for the above example.

**Comment by zupo** [comment]
As per https://github.com/p1c2u/openapi-schema-validator/issues/22, have you tried using `openapi-schema-validator` version `0.3.0`?

**Comment by bushkov** [comment]
> As per https://github.com/p1c2u/openapi-schema-validator/issues/22, have you tried using openapi-schema-validator version 0.3.0?

Yes, I still get the error even with `openapi-schema-validator` version `0.3.0`.

**Comment by zupo** [comment]
That is indeed strange. I'll try to take a look in the not too distant future. Any help debugging this is greatly appreciated. If you have any additional info, please share. Or even a failing tests that showcases exactly how the thing fails.

**Comment by bushkov** [comment]
> Any help debugging this is greatly appreciated. If you have any additional info, please share. Or even a failing tests that showcases exactly how the thing fails.

You can use the example with the modified TODO app which I mentioned in my first comment of this issue. If you modify the TODO app following the instructions in the comment and then execute the tests from the TODO app directory, the tests will fail with:
```
webtest.app.AppError: Bad response: 500 Internal Server Error (not 200)
b'[{"exception":"ValidationError","message":"None for not nullable"}]'
```

**Comment by wilsonjsq** [comment]
@zupo any update for this issue? We;re also running into the same problem as this example.

**Comment by zupo** [comment]
The entire `nullable` story seems to have been rewritten in OpenAPI v3.1. This library does not yet support v3.1, but work is in progress: https://github.com/Pylons/pyramid_openapi3/pull/206

**Comment by miketheman** [comment]
The minimum version of `openapi-core` supported by `pyramid_openapi3` is 0.19.1, and their [minimum version of `openapi-schema-validator` is 0.6.0](https://github.com/python-openapi/openapi-core/blob/059dd73652f6ac4dd45e683f202d0764c7971b72/pyproject.toml#L72) which contains the deeper fix where both the 3.0 (`nullable: true` via `$ref`) and 3.1 (`type: [..., "null"]` via `$ref`) cases now validate `null` correctly.

Closing!
